local GRAY_ARROWS_Y_REVERSE  = require "Helper.GRAY_ARROWS_Y_REVERSE";
local GRAY_ARROWS_Y_STANDARD = require "Helper.GRAY_ARROWS_Y_STANDARD";

return (GRAY_ARROWS_Y_STANDARD + GRAY_ARROWS_Y_REVERSE) / 2;
